import { fileURLToPath } from "node:url";
import { loadEnv } from "@bot/config";
import { createLogger } from "@bot/logger";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { createDatabase } from "./client";

/**
 * Apply pending SQL migrations (generated by `pnpm db:generate`) and exit.
 * Run it before starting the gateway:
 *
 *   node --env-file=.env apps/api-gateway/dist/migrate.js
 */
async function main(): Promise<void> {
  const logger = createLogger({ name: "api-gateway-migrate" });
  const env = loadEnv();
  const { db, pool } = createDatabase(env.DATABASE_URL);
  try {
    // Resolved from the BUNDLED location (dist/migrate.js): ../drizzle is the
    // app root's migration folder. Always run the built script, not src/.
    const migrationsFolder = fileURLToPath(new URL("../drizzle", import.meta.url));
    await migrate(db, { migrationsFolder });
    logger.info("migrations applied");
  } finally {
    await pool.end();
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
